CREATE TABLE products (
	id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	created timestamp NOT NULL,
	updated timestamp NOT NULL,
	description varchar(500) NOT NULL,
	name varchar(100) NOT NULL,
	price numeric(3) NOT NULL,
	CONSTRAINT products_pkey PRIMARY KEY (id)
);