insert into cozinha (nome) values ('Tailandeza');
insert into cozinha (nome) values ('Portuguesa');
insert into cozinha (nome) values ('Italiana');
insert into cozinha (nome) values ('Mineira');
insert into cozinha (nome) values ('Brasileira');
insert into restaurante (nome, taxa_frete, id_cozinha, data_cadastro, data_atualizacao) values ('Thai Gourmet', 10, 1, utc_timestamp, utc_timestamp);
insert into restaurante (nome, taxa_frete, id_cozinha, data_cadastro, data_atualizacao) values ('Thai Delivery', 9.50, 5, utc_timestamp, utc_timestamp);
insert into restaurante (nome, taxa_frete, id_cozinha, data_cadastro, data_atualizacao) values ('Cantina Vassoler', 15, 3, utc_timestamp, utc_timestamp);
insert into estado (nome) values ('Parana');
insert into estado (nome) values ('São Paulo');
insert into estado (nome) values ('Minas Gerais');
insert into estado (nome) values ('Rio de Janeiro');